
name: CI

on:
  schedule:
    - cron: "*/30 * * * *"  
    # scheduled at 1 MIN every day 
  workflow_dispatch:
jobs:
  sync_with_upstream:
    runs-on: ubuntu-latest
    
    steps:
    - name: Pull upstream changes
      id: sync
      uses: tgymnich/fork-sync@v1.4
      with:
        # token: ${{ secrets.ACCESS_TOKEN }}
        owner: freev2
        base: main
        head: main

       

    - name: Timestamp
      run: date
